-- models/marts/students_demo_2023.sql
SELECT 
    s.REGION,
    s.YEAR_PATH_STARTED AS ANNEE,
    s.AGE_GROUP,
    s.GENDER,
    COUNT(s.USER_ID) AS NB_STUDENTS,
    MAX(p.POPULATION) AS POPULATION,
    MAX(r.REVENU_DISPONIBLE_BRUT) AS REVENUE_BRUT_DISPO,
    ROUND(
        (COUNT(s.USER_ID) / NULLIF(MAX(p.POPULATION), 0)) * 100000,
    2) AS STUDENTS_PER_100K
FROM {{ ref('stg_students') }} s
LEFT JOIN {{ ref('population_region_2023') }} p 
    ON UPPER(TRIM(s.REGION)) = UPPER(TRIM(p.REGION))
LEFT JOIN {{ ref('revenu_region_2023') }} r 
    ON UPPER(TRIM(s.REGION)) = UPPER(TRIM(r.REGION))
GROUP BY s.REGION, s.YEAR_PATH_STARTED, s.AGE_GROUP, s.GENDER
ORDER BY s.REGION, s.YEAR_PATH_STARTED, s.AGE_GROUP
